name: MPVP
version: '${project.version}'
main: com.megaearth.mpvp.MPVP
api-version: '1.20'
commands:
    settings:
        description: A command to open the settings GUI
        usage: /<command>
        aliases: []
        default: true
        permission-message: You don't have permission to use this command.
        executor: com.megaearth.mpvp.commands.SettingsCommand
    play:
        description: A command to open the play GUI
        usage: /<command>
        aliases: []
        default: true
        permission-message: You don't have permission to use this command.
        executor: com.megaearth.mpvp.commands.PlayCommand
