name: Mega-Lobby
version: '${project.version}'
main: com.megaearth.mlobby.mlobby
api-version: '1.20'
commands:
        gui:
            description: A command to open the GUI
            usage: /<command>
            aliases: [play, p]
            default: true
            permission-message: You don't have permission to use this command.
        queue:
            description: A command to join/leave the queue
            usage: /<command>
            aliases: [q]
            default: true
            args: [join, leave, list, listqueues]
            permission-message: You don't have permission to use this command.
        debug:
            description: A command to debug the plugin
            usage: /<command>
            aliases: [d]
            default: true
            args: []
            permission-message: You don't have permission to use this command.