name: MPVP
version: '${project.version}'
main: com.megaearth.mpvp.MPVP
api-version: '1.20'
commands:
        gui:
            description: A command to open the GUI
            usage: /<command>
            aliases: [play, p]
            default: true
            permission-message: You don't have permission to use this command.
            executor: com.megaearth.mpvp.PlayGUI
        queue:
            description: A command to join/leave the queue
            usage: /<command>
            aliases: [q]
            default: true
            args: [join, leave, list, listqueues]
            permission-message: You don't have permission to use this command.
            executor: com.megaearth.mpvp.commands.QueueManager
